### ISSUE TITLE
添加包的依赖管理

### ISSUE THREAD

**Issue by gaoxinge** [dubbo/dubbo-go#8]
能否使用go dep或者go mod来管理包？

**Comment by gaoxinge** [comment]
`dep init` 结果如下：https://github.com/gaoxinge/dubbo-go/commit/fef8e04f458e0455cafb534ff03033fd6ec2258b

**Comment by AlexStocks** [comment]
能否提交一个pr？

**Comment by complone** [comment]
是这样的，可以把第三方包clone到项目的同级目录下，这样一旦有项目clone到本地，goland就会及时提示是否需要使用```go get```。```go mod```目前只支持``` go1.11```

**Comment by complone** [comment]
> 能否使用go dep或者go mod来管理包？

是这样的，可以把第三方包clone到项目的同级目录下，这样一旦有项目clone到本地，goland就会及时提示是否需要使用go get。go mod目前只支持 go1.11

**Comment by AlexStocks** [comment]
@complone go 1.11之后的版本确实才提供 go mod，这个我个人目前也不建议使用。但 @gaoxinge 也给了一个 go dep，这个是可以的。所以等待 @gaoxinge 提交一个 pr。

**Comment by gaoxinge** [comment]
提交了一个pr：https://github.com/dubbo/dubbo-go/pull/9

**Comment by AlexStocks** [comment]
@gaoxinge 为何把 gopkg.lock 和 vendor 放在 .gitignore 呢？

**Comment by gaoxinge** [comment]
@AlexStocks 把`*.pkg`和`vendor`加入`.gitignore`主要有两方面的考虑：

- 有了`*.toml`文件之后，就了依赖关系，不需要明确`*.pkg`和`vendor`
- 另外，我担心`vendor`文件占用过多空间，所以把`vendor`加到了`.gitignore`里面

**Comment by AlexStocks** [comment]
@gaoxinge 你进下钉钉群 21940181，我们正在讨论这个事。
